name: escritorio_advocacia_especilizado
description: "projeto flutter escritorio advocacia."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  mdi: ^5.0.0-nullsafety.0
  url_launcher: ^6.2.5
  swipperview: ^0.0.3+13
  table_calendar: ^3.1.1
  intl: ^0.19.0
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_typeahead: ^5.2.0
  screenshot: ^2.3.0
  syncfusion_flutter_datepicker: ^25.1.42
  custom_text_form_field_plus: ^0.0.5
    #FIREBASE
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_messaging: ^14.7.19
    #FIM FIREBASE
    #BLOC
  bloc_pattern: ^3.0.1
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  #
  flutter_lints: ^3.0.0




flutter:

  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/logo.png
    - assets/logo_losangulo.png
    - assets/capa.jpeg
    - assets/nova_logo.png


